listen: ":8080"
secret: "I am a hero"
cmds:
  - cmd:
      type: 0
      arg: "ls"
      desc: "example readonly command"
  - cmd:
      type: 1
      arg: "ls -al"
      desc: "another readonly command"

